
import java.util.*;

import java.io.File;

import javax.swing.DefaultListModel;

 
import java.util.ArrayList;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ricardo
 */
public class PlayerView extends javax.swing.JFrame {
    File musicola;
    boolean shuffle;
    String songFile;
    String currentPath;
    boolean repeat = false;
    ArrayList <String> songs;
    ArrayList <String> shuff;
    int xMouse, yMouse;
    private Controller control;
    File homedir = new File(System.getProperty("user.home"));
    DefaultListModel listitem= new DefaultListModel();
    
    
    
    
    
    
    public PlayerView(ArrayList <String> array, Controller contr) {
        initComponents();
        control=contr;
        boolean shuffle=false;
        songs=new ArrayList<String>();
        
        songs.add("champs.mp3");
        songs.add("music.mp3");
        
       
       
        for(int i=0; i<songs.size(); i++){
        listitem.addElement(songs.get(i));
        listaMusica.setModel(listitem);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlayerPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaMusica = new javax.swing.JList<>();
        backbtn = new javax.swing.JLabel();
        startplaylistbtn = new javax.swing.JLabel();
        shufflebtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PlayerPanel.setBackground(new java.awt.Color(110, 2, 2));
        PlayerPanel.setForeground(new java.awt.Color(255, 3, 0));
        PlayerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Liberation Mono", 0, 24)); // NOI18N
        jLabel3.setText("Media Center");
        PlayerPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, 46));

        listaMusica.setBackground(new java.awt.Color(23, 77, 104));
        listaMusica.setFont(new java.awt.Font("Liberation Mono", 0, 18)); // NOI18N
        listaMusica.setForeground(new java.awt.Color(69, 64, 64));
        listaMusica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaMusicaMouseClicked(evt);
            }
        });
        listaMusica.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaMusicaValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaMusica);

        PlayerPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 150, 230));

        backbtn.setFont(new java.awt.Font("Liberation Mono", 0, 24)); // NOI18N
        backbtn.setText("X");
        backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbtnMouseClicked(evt);
            }
        });
        PlayerPanel.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 16, -1));

        startplaylistbtn.setText("<- Começar PlayList");
        startplaylistbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startplaylistbtnMouseClicked(evt);
            }
        });
        PlayerPanel.add(startplaylistbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 181, 59));

        shufflebtn.setText("SHUFFLE OFF");
        shufflebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shufflebtnMouseClicked(evt);
            }
        });
        PlayerPanel.add(shufflebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 155, 113));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setAlignmentX(5.0F);
        jLabel1.setAlignmentY(5.0F);
        jLabel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel1FocusGained(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        PlayerPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PlayerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PlayerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(610, 370));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void shufflebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shufflebtnMouseClicked
        if(shuffle==true) {
            shufflebtn.setText("SHUFFLE OFF");
            shuffle = false;
        }

        else {shufflebtn.setText("SHUFFLE ON");
            shuffle = true;
            shuff=songs;
            Collections.shuffle(shuff);
            //jPanel1.setBackground(Color.green);
        }
    }//GEN-LAST:event_shufflebtnMouseClicked

    private void startplaylistbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startplaylistbtnMouseClicked
        String playlist= "vlc ";
        ArrayList<String> pllist;

        pllist =songs;
        if(shuffle==true){
            pllist =shuff;
        }
        for (String s : pllist)
        {
            playlist += "Música/" + s + "\t";
        }
        try{Process process = Runtime.getRuntime().exec(playlist);
        }
        catch(Exception w){}

    }//GEN-LAST:event_startplaylistbtnMouseClicked

    private void backbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseClicked
        this.dispose();
    }//GEN-LAST:event_backbtnMouseClicked

    private void listaMusicaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaMusicaValueChanged

    }//GEN-LAST:event_listaMusicaValueChanged

    private void listaMusicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaMusicaMouseClicked
        this.control.playOneSong(listaMusica.getSelectedValue());

    }//GEN-LAST:event_listaMusicaMouseClicked

    private void jLabel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1FocusGained

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PlayerPanel;
    private javax.swing.JLabel backbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaMusica;
    private javax.swing.JLabel shufflebtn;
    private javax.swing.JLabel startplaylistbtn;
    // End of variables declaration//GEN-END:variables
   
}
